# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0070_auto_20170923_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='id_organismo_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo'),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 16, 13, 48, 356000)),
        ),
    ]
