# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0071_auto_20170923_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 16, 56, 9, 717000)),
        ),
    ]
