# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0072_auto_20170923_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='municipio',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 16, 59, 35, 898000)),
        ),
    ]
