# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0073_auto_20170923_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Centro',
            fields=[
                ('identificador', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 17, 20, 37, 174000)),
        ),
    ]
