# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-23 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0074_auto_20170923_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Centro',
            new_name='Tipo_Entidad',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 17, 53, 35, 346000)),
        ),
    ]
