# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-24 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0075_auto_20170923_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_entidad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 23, 18, 1, 24, 645000)),
        ),
    ]
