# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0079_auto_20170924_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_entidad',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='tipo_entidad',
            old_name='nombre_tipo',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 18, 15, 20, 561000)),
        ),
    ]
