# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 00:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0080_auto_20170924_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_entidad',
            options={'ordering': ['nombre_entidad']},
        ),
        migrations.RenameField(
            model_name='tipo_entidad',
            old_name='name',
            new_name='nombre_entidad',
        ),
        migrations.AlterField(
            model_name='entidad',
            name='id_organismo_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='id_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Tipo_Entidad'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 24, 18, 22, 11, 248000)),
        ),
    ]
