# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-25 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0081_auto_20170924_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_entidad',
            options={'ordering': ['nombre_tipo']},
        ),
        migrations.RenameField(
            model_name='tipo_entidad',
            old_name='nombre_entidad',
            new_name='nombre_tipo',
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 11, 31, 20)),
        ),
    ]
