# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 18:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0082_auto_20170925_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaGraduados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_demanda', models.CharField(max_length=255, unique=True)),
                ('anno_realizacion', models.IntegerField(blank=True, null=True)),
                ('anno_mas_uno', models.IntegerField(blank=True, null=True)),
                ('anno_mas_dos', models.IntegerField(blank=True, null=True)),
                ('anno_mas_tres', models.IntegerField(blank=True, null=True)),
                ('anno_mas_cuatro', models.IntegerField(blank=True, null=True)),
                ('anno_mas_cinco', models.IntegerField(blank=True, null=True)),
                ('anno_mas_seis', models.IntegerField(blank=True, null=True)),
                ('anno_mas_siete', models.IntegerField(blank=True, null=True)),
                ('anno_mas_ocho', models.IntegerField(blank=True, null=True)),
                ('anno_mas_nueve', models.IntegerField(blank=True, null=True)),
                ('anno_mas_diez', models.IntegerField(blank=True, null=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Carrera')),
            ],
            options={
                'ordering': ['codigo_demanda'],
            },
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'ordering': ['e_nombre']},
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 14, 3, 32, 503000)),
        ),
        migrations.AddField(
            model_name='demandagraduados',
            name='entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Entidad'),
        ),
        migrations.AddField(
            model_name='demandagraduados',
            name='municipio_entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
        ),
        migrations.AddField(
            model_name='demandagraduados',
            name='organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo'),
        ),
    ]
