# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 16:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0085_auto_20171016_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id_ocupados', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('id_tipo_plaza', models.CharField(choices=[(b'CI', b'Indeterminado'), (b'CDSS', b'Determinado en cumplimiento del servicio social'), (b'RCCI', b'Reserva cient\xc3\xadfica CI'), (b'RCCD', b'Reserva cient\xc3\xadfica CD'), (b'DIC', b'Determinado ICRT y MINCULT')], max_length=255)),
                ('id_rango_edad', models.CharField(choices=[(b'-31', b'Menores de 31 a\xc3\xb1os'), (b'31<x<50', b'De 31 a 50 a\xc3\xb1os'), (b'51<x<60', b'De 51 a 60 a\xc3\xb1os'), (b'+60', b'Mayores de 60 a\xc3\xb1os')], max_length=255)),
                ('cant_graduados', models.IntegerField(blank=True, null=True)),
                ('ano_realizacion', models.IntegerField(blank=True, null=True)),
                ('id_cod_carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Carrera')),
                ('id_codigo_entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Entidad')),
                ('id_municipio_ocupado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio')),
            ],
        ),
        migrations.AlterModelOptions(
            name='demandagraduados',
            options={},
        ),
        migrations.RemoveField(
            model_name='demandagraduados',
            name='id',
        ),
        migrations.AlterField(
            model_name='demandagraduados',
            name='codigo_demanda',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 12, 44, 12, 236000)),
        ),
    ]
