# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0086_auto_20171101_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fluctuacion',
            fields=[
                ('id_fluctuacion', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('anno_realizacion', models.IntegerField(blank=True, null=True)),
                ('id_carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Carrera')),
            ],
        ),
        migrations.AlterField(
            model_name='causal_movimiento',
            name='tipo',
            field=models.CharField(choices=[(b'ml', b'Movimiento Laboral'), (b'i', b'Inhabilitaci\xc3\xb3n'), (b'f', b'Fluctuaci\xc3\xb3n')], max_length=90),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 13, 8, 30, 276000)),
        ),
        migrations.AddField(
            model_name='fluctuacion',
            name='id_causal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Causal_movimiento'),
        ),
        migrations.AddField(
            model_name='fluctuacion',
            name='id_entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Entidad'),
        ),
        migrations.AddField(
            model_name='fluctuacion',
            name='id_munic_entidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Municipio'),
        ),
    ]
