# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-15 21:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0087_auto_20171102_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 16, 7, 51, 308000)),
        ),
    ]
