# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-12 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0100_auto_20171201_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencia',
            name='id_organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo'),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 12, 36, 24, 972000)),
        ),
    ]
