# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-13 16:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGMGU', '0101_auto_20171212_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluctuacion',
            name='id_organismo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SGMGU.Organismo'),
        ),
        migrations.AlterField(
            model_name='expediente_aprobado',
            name='fecha_aprobado',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 13, 11, 16, 4, 939000)),
        ),
    ]
